"""
g_gene_enrichment.py
--------------------
Robustness check: do GxE-ASE enrichment signals reflect something specific to
environment-dependent allele-specific expression, or do they arise from general
constitutive cis-regulatory divergence between B73 and Mo17?

The concern: GxE genes necessarily have allele-specific differences in at least
one environment, which creates potential overlap with G (constitutive ASE) genes.
If SV and DAP-seq signals are driven by general B73/Mo17 cis divergence, G genes
should show equal or stronger enrichment than GxE genes.

Approach: partition the pre-filtered universe into four mutually exclusive groups
and compare enrichment for each relative to the "Neither" baseline:

  GxE-only  — GxE-ASE (padj < 0.1) but NOT constitutive G-ASE
  G-only    — constitutive G-ASE (padj < 0.1 in both envs, same direction) but NOT GxE
  GxE+G     — both GxE-ASE and constitutive G-ASE
  Neither   — in the expressed universe, neither GxE nor G (reference group)

Tests (Fisher exact + Mann-Whitney U, each group vs "Neither"):
  • SNPs in promoter
  • Small indels (< 50 bp) in promoter
  • Large indels (> 50 bp) in promoter
  • Genotype-specific DAP-seq peak in promoter
  • SNP overlapping a genotype-specific DAP-seq peak
  • Small indel overlapping a genotype-specific DAP-seq peak

Reads:
  data/GxE_gene_IDs.txt
  data/G_gene_IDs.txt          ← generated by 1_deseq_analysis.R
  data/background_gene_IDs.txt
  results/sv_per_gene.tsv      ← needs script 3 rerun with SNPs VCF for n_SNP
  results/dap_seq_per_gene.tsv ← needs script 2b rerun for n_snp_genotype_spec
  results/indel_dap_overlap_per_gene.tsv  ← fallback for small-indel×DAP

Produces:
  results/g_gene_enrichment.tsv
  figures/g_gene_enrichment_figure.png
"""

import numpy as np
import pandas as pd
from scipy.stats import fisher_exact, mannwhitneyu
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

BASE    = "./"
DATA    = f"{BASE}/data"
RESULTS = f"{BASE}/results"
FIGURES = f"{BASE}/figures"

# ── 1. Load gene sets ─────────────────────────────────────────────────────────
print("Loading gene sets …")
gxe_ids = set(open(f"{DATA}/GxE_gene_IDs.txt").read().split())
bg_ids  = set(open(f"{DATA}/background_gene_IDs.txt").read().split())
g_ids   = set(open(f"{DATA}/G_gene_IDs.txt").read().split())

universe = gxe_ids | bg_ids

# Four mutually exclusive groups within the universe.
# G ⊆ universe is guaranteed by 1_deseq_analysis.R restricting sig_g to universe,
# so G - GxE ⊆ bg_ids and the groups are fully disjoint and exhaustive.
gxe_only = gxe_ids - g_ids
g_only   = g_ids   - gxe_ids
gxe_g    = gxe_ids & g_ids
neither  = bg_ids  - g_ids

assert len(gxe_only) + len(g_only) + len(gxe_g) + len(neither) == len(universe), \
    "Groups don't partition universe — check that G_gene_IDs.txt was built from the same universe"

print(f"\n{'─'*56}")
print(f"{'Universe:':<20} {len(universe):>7,}")
print(f"{'GxE genes:':<20} {len(gxe_ids):>7,}")
print(f"{'G genes:':<20} {len(g_ids):>7,}")
print(f"{'GxE ∩ G:':<20} {len(gxe_g):>7,}  "
      f"({100*len(gxe_g)/len(gxe_ids):.1f}% of GxE, "
      f"{100*len(gxe_g)/max(len(g_ids),1):.1f}% of G)")
print(f"{'─'*56}")
print(f"{'Four groups:'}")
print(f"  {'GxE-only:':<16} {len(gxe_only):>7,}")
print(f"  {'G-only:':<16} {len(g_only):>7,}")
print(f"  {'GxE+G:':<16} {len(gxe_g):>7,}")
print(f"  {'Neither:':<16} {len(neither):>7,}  (reference)")
print(f"{'─'*56}\n")

# ── 2. Load and merge per-gene enrichment data ────────────────────────────────
print("Loading per-gene data …")
dap  = pd.read_csv(f"{RESULTS}/dap_seq_per_gene.tsv",           sep="\t")
sv   = pd.read_csv(f"{RESULTS}/sv_per_gene.tsv",                sep="\t")
olap = pd.read_csv(f"{RESULTS}/indel_dap_overlap_per_gene.tsv", sep="\t")

# Promoter-level variant counts from sv_per_gene.tsv
sv_cols = ["gene", "n_small_indel", "n_large_indel"]
has_snp_sv = "n_SNP" in sv.columns
if has_snp_sv:
    sv_cols.append("n_SNP")
else:
    print("  NOTE: n_SNP not found in sv_per_gene.tsv — rerun script 3 with SNPs VCF")

# Variant × DAP overlap counts.
# Preferred source: dap_seq_per_gene.tsv (new columns from script 2b rerun).
# Fallback: indel_dap_overlap_per_gene.tsv (small indels only, all versions).
has_snp_dap   = "n_snp_genotype_spec"         in dap.columns
has_si_dap_new = "n_small_indel_genotype_spec" in dap.columns

dap_cols = ["gene", "n_diff"]
if has_snp_dap:
    dap_cols.append("n_snp_genotype_spec")
else:
    print("  NOTE: n_snp_genotype_spec not in dap_seq_per_gene.tsv — rerun script 2b")
if has_si_dap_new:
    dap_cols.append("n_small_indel_genotype_spec")

df = (dap[dap_cols].rename(columns={"n_diff": "n_diff_dap"})
      .merge(sv[sv_cols], on="gene", how="inner"))

# Small-indel × DAP: prefer new column from dap, fall back to olap file
if has_si_dap_new:
    df = df.rename(columns={"n_small_indel_genotype_spec": "n_indel_dap"})
else:
    df = df.merge(olap[["gene", "n_genotype_spec"]].rename(
                      columns={"n_genotype_spec": "n_indel_dap"}),
                  on="gene", how="left")

df["n_indel_dap"] = df["n_indel_dap"].fillna(0).astype(int)
if has_snp_dap:
    df["n_snp_genotype_spec"] = df["n_snp_genotype_spec"].fillna(0).astype(int)

# Assign group membership via dict lookup (O(1) per gene)
group_map = (
    {g: "GxE-only" for g in gxe_only} |
    {g: "G-only"   for g in g_only}   |
    {g: "GxE+G"    for g in gxe_g}    |
    {g: "Neither"  for g in neither}
)
df["group"] = df["gene"].map(group_map)
df = df[df["group"].notna()].reset_index(drop=True)

# Binary feature columns — always present
df["has_small_indel"] = df["n_small_indel"] > 0
df["has_large_indel"] = df["n_large_indel"] > 0
df["has_diff_dap"]    = df["n_diff_dap"]    > 0
df["has_indel_dap"]   = df["n_indel_dap"]   > 0

# Conditionally present columns
if has_snp_sv:
    df["n_SNP"]    = df["n_SNP"].fillna(0).astype(int)
    df["has_snp"]  = df["n_SNP"] > 0
if has_snp_dap:
    df["has_snp_dap"] = df["n_snp_genotype_spec"] > 0

# Build METRICS list depending on which data are available
METRICS = []
if has_snp_sv:
    METRICS.append(("has_snp",        "n_SNP",                 "SNPs\nin promoter"))
METRICS.append(    ("has_small_indel", "n_small_indel",        "Small indels\nin promoter"))
METRICS.append(    ("has_large_indel", "n_large_indel",        "Large indels\nin promoter"))
METRICS.append(    ("has_diff_dap",    "n_diff_dap",           "Genotype-specific\nDAP peak"))
if has_snp_dap:
    METRICS.append(("has_snp_dap",    "n_snp_genotype_spec",  "SNP ×\nDAP peak"))
METRICS.append(    ("has_indel_dap",  "n_indel_dap",          "Small indel ×\nDAP peak"))

# ── 3. Enrichment tests ───────────────────────────────────────────────────────
print("── Enrichment tests (each group vs 'Neither') ──────────────────────")

ref_df = df[df["group"] == "Neither"]
n_ref  = len(ref_df)

rows = []
for grp in ["GxE-only", "G-only", "GxE+G"]:
    g_df = df[df["group"] == grp]
    n_g  = len(g_df)
    print(f"\n  {grp}  (n={n_g:,}) vs Neither (n={n_ref:,}):")
    for has_col, cnt_col, label in METRICS:
        has_g = int(g_df[has_col].sum())
        has_r = int(ref_df[has_col].sum())
        OR, p_fish = fisher_exact([[has_g,   n_g   - has_g],
                                   [has_r,   n_ref - has_r]])
        _, mwu_p = mannwhitneyu(g_df[cnt_col].fillna(0),
                                ref_df[cnt_col].fillna(0),
                                alternative="greater")
        pct_g = 100 * has_g / n_g   if n_g   else 0.0
        pct_r = 100 * has_r / n_ref if n_ref else 0.0
        metric_flat = label.replace("\n", " ")
        print(f"    {metric_flat:35s}  "
              f"{pct_g:5.1f}% vs {pct_r:5.1f}%  "
              f"OR={OR:.3f}  Fisher p={p_fish:.4g}  MWU p={mwu_p:.4g}")
        rows.append(dict(group=grp, metric=metric_flat,
                         n_group=n_g, n_ref=n_ref,
                         has_group=has_g, has_ref=has_r,
                         pct_group=pct_g, pct_ref=pct_r,
                         fisher_OR=OR, fisher_p=p_fish, mwu_p=mwu_p))

results_df = pd.DataFrame(rows)

# ── 4. Figure ─────────────────────────────────────────────────────────────────
print("\nGenerating figure …")

GROUP_ORDER  = ["GxE-only", "G-only", "GxE+G", "Neither"]
TEST_GROUPS  = ["GxE-only", "G-only", "GxE+G"]   # the three bars in OR panels
GROUP_COLORS = {
    "GxE-only": "#2196F3",
    "G-only":   "#FF9800",
    "GxE+G":    "#9C27B0",
    "Neither":  "#BDBDBD",
}

n_metrics = len(METRICS)
fig, axes = plt.subplots(2, n_metrics, figsize=(4.0 * n_metrics, 9))
fig.subplots_adjust(hspace=0.50, wspace=0.38)

bar_w = 0.55

for col_i, (has_col, cnt_col, label) in enumerate(METRICS):

    # ── Top row: % genes with feature, all four groups ────────────────────────
    ax_top = axes[0, col_i]
    x4 = np.arange(len(GROUP_ORDER))
    pcts = [100 * df[df["group"] == g][has_col].mean() for g in GROUP_ORDER]
    bars = ax_top.bar(x4, pcts,
                      color=[GROUP_COLORS[g] for g in GROUP_ORDER],
                      width=bar_w, edgecolor="black", lw=0.5)
    for bar, val in zip(bars, pcts):
        ax_top.text(bar.get_x() + bar.get_width() / 2,
                    bar.get_height() + max(pcts) * 0.01,
                    f"{val:.1f}%", ha="center", va="bottom", fontsize=7.5)
    ax_top.set_xticks(x4)
    ax_top.set_xticklabels(GROUP_ORDER, rotation=30, ha="right", fontsize=8)
    ax_top.set_ylabel("% genes with feature", fontsize=8.5)
    ax_top.set_title(f"{chr(65 + col_i)}  {label}",
                     fontsize=9.5, fontweight="bold")
    ax_top.set_ylim(0, max(pcts) * 1.18)

    # ── Bottom row: Fisher OR vs "Neither", test groups only ─────────────────
    ax_bot = axes[1, col_i]
    x3  = np.arange(len(TEST_GROUPS))
    ors = []
    ps  = []
    metric_flat = label.replace("\n", " ")
    for grp in TEST_GROUPS:
        row = results_df[(results_df["group"] == grp) &
                         (results_df["metric"] == metric_flat)]
        if len(row):
            ors.append(float(row["fisher_OR"].iloc[0]))
            ps.append(float(row["fisher_p"].iloc[0]))
        else:
            ors.append(1.0); ps.append(1.0)

    bars2 = ax_bot.bar(x3, ors,
                       color=[GROUP_COLORS[g] for g in TEST_GROUPS],
                       width=bar_w, edgecolor="black", lw=0.5)
    ax_bot.axhline(1.0, color="black", lw=0.9, ls="--", zorder=0)

    y_top = max(max(ors), 1.05)
    for bar, val, p in zip(bars2, ors, ps):
        sig = ("***" if p < 0.001 else
               "**"  if p < 0.01  else
               "*"   if p < 0.05  else "ns")
        ax_bot.text(bar.get_x() + bar.get_width() / 2,
                    max(val, 1.0) + y_top * 0.02,
                    f"{val:.2f}\n{sig}", ha="center", va="bottom", fontsize=7.5)

    ax_bot.set_xticks(x3)
    ax_bot.set_xticklabels(TEST_GROUPS, rotation=30, ha="right", fontsize=8)
    ax_bot.set_ylabel("Fisher OR vs Neither", fontsize=8.5)
    ax_bot.set_title(f"{chr(69 + col_i)}  OR vs Neither", fontsize=9.5, fontweight="bold")
    ax_bot.set_ylim(0, y_top * 1.22)

# Group size legend as subtitle
sizes = {g: len(df[df["group"] == g]) for g in GROUP_ORDER}
size_txt = "   ".join(f"{g}  n={sizes[g]:,}" for g in GROUP_ORDER)
fig.suptitle(
    "Enrichment signals by GxE-ASE vs constitutive-ASE (G) gene status",
    fontsize=12, fontweight="bold", y=0.98
)
fig.text(0.5, 0.945, size_txt, ha="center", fontsize=8.5, color="#444444")

out_fig = f"{FIGURES}/g_gene_enrichment_figure.png"
fig.savefig(out_fig, dpi=150, bbox_inches="tight")
plt.close()
print(f"  Saved → {out_fig}")

# ── 5. Save results table ─────────────────────────────────────────────────────
results_df.to_csv(f"{RESULTS}/g_gene_enrichment.tsv", sep="\t", index=False)
print(f"  Saved → {RESULTS}/g_gene_enrichment.tsv")

print("\nDone.")
